labels:
  platform: linux/arm64

steps: 
   - name: terraform plan 
     image: ghcr.io/pintz-org/asdf-terraform:1.8.2_debug
     settings:
       command: "init"
       path: "test/terraform"

   - name: terraform plan 
     image: ghcr.io/pintz-org/asdf-terraform:1.8.2_debug
     settings:
       command: "plan -lock=false"
       path: "test/terraform"

   - name: terraform auto-approve 
     image: ghcr.io/pintz-org/asdf-terraform:1.8.2_debug 
     settings:
       command: "apply -auto-approve -lock=false"
       path: "test/terraform"

