labels:
  platform: linux/arm64

steps: 
   - name: terraform init 
     image: ghcr.io/pintz-org/asdf-terraform:1.8.2_debug
     settings:
       command: "init"
       path: "test/terraform"

   - name: terraform plan 
     image: ghcr.io/pintz-org/asdf-terraform:1.8.2_debug
     settings:
       command: "plan"

   - name: terraform auto-approve 
     image: ghcr.io/pintz-org/asdf-terraform:1.8.2_debug 
     settings:
       command: "apply"

