labels:
  platform: linux/arm64

steps: 
   - name: publish-poetry 
     image: woodpeckerci/plugin-docker-buildx
     settings:
       registry: ghcr.io
       repo: ghcr.io/pintz-org/asdf-poetry 
       dockerfile: poetry/Dockerfile
       platforms: linux/amd64,linux/arm64/v8
       tag: 1.8.3
       username: pintz
       password:
         from_secret: github_pat

