labels:
  platform: linux/arm64

steps:
  - name: test terraform init 
    image: ghcr.io/pintz-org/asdf-terraform:1.8.2
    pull: true
    settings:
      command: "init"
      path: "test/terraform"

  - name: test terraform plan 
    image: ghcr.io/pintz-org/asdf-terraform:1.8.2
    pull: true
    settings:
      command: "plan"
      path: "test/terraform"

  - name: test terraform auto-approve 
    image: ghcr.io/pintz-org/asdf-terraform:1.8.2 
    pull: true
    settings:
      command: 'apply --auto-approve'
      path: "test/terraform"

